# Schema for configuration files of the Search API Federated Solr module.

search_api_federated_solr.search_app.settings:
  type: config_object
  label: 'Search API Federated Solr settings'
  mapping:
    path:
      type: string
      label: 'The path for the search app.'
    facet:
      type: mapping
      mapping:
        site_name:
          type: mapping
          mapping:
            set_default:
              type: boolean
              label: 'When true, only search results from this site will be shown.'
            is_hidden:
              type: boolean
              label: 'When true, this facet option is hidden in the UI.'
        federated_type:
          type: mapping
          mapping:
            is_hidden:
              type: boolean
              label: 'When true, this facet option is hidden in the UI.'
        federated_terms:
          type: mapping
          mapping:
            is_hidden:
              type: boolean
              label: 'When true, this facet option is hidden in the UI.'
    filter:
      type: mapping
      mapping:
        federated_date:
          type: mapping
          mapping:
            is_hidden:
              type: boolean
              label: 'When true, this filter option is hidden in the UI.'
    index:
      type: mapping
      mapping:
        id:
          type: string
          label: 'Defines which search_api index and server the search app should use.'
        has_federated_date_property:
          type: boolean
          label: 'Has federated date flag.'
        has_federated_terms_property:
          type: boolean
          label: 'Has federated terms flag.'
        has_federated_type_property:
          type: boolean
          label: 'Has federated type flag.'
        has_site_name_property:
          type: boolean
          label: 'Has site name flag.'
        server_url:
          type: string
          label: 'The server url for the search app.'
        username:
          type: string
          label: 'Basic Auth username.'
        password:
          type: string
          label: 'Basic Auth password.'
    content:
      type: mapping
      mapping:
        no_results:
          type: string
          label: 'This text is shown when a query returns no results.'
        search_prompt:
          type: string
          label: 'This text is shown when no query term has been entered.'
        show_empty_search_results:
          type: integer
          label: 'Flag to render search page as a listing page with all results rendering when no search term is entered.'
    results:
      type: mapping
      mapping:
        rows:
          type: integer
          label: 'The max number of results to render per search results page.'
    pagination:
      type: mapping
      mapping:
        buttons:
          type: integer
          label: 'The max number of numbered pagination buttons to show at a given time.'
    autocomplete:
      type: mapping
      mapping:
        isEnabled:
          type: integer
          label: 'When true, autocomplete is enabled for the search app.'
        url:
          type: string
          label: 'The autocomplete endpoint url to be used.'
        appendWildcard:
          type: integer
          label: 'When checked, the query will have a wildcard appended.'
        suggestionRows:
          type: string
          label: 'The number of results to return from the autocomplete request.'
        numChars:
          type: string
          label: 'The number of characters, after which the autocomplete request should be made.'
        mode:
          type: string
          label: 'The type of results returned by the autocomplete request: results or terms.'
        result:
          type: mapping
          mapping:
            titleText:
              type: string
              label: 'The title text for the autocomplete results.'
            hideDirectionsText:
              type: integer
              label: 'When true, the keyboard directions text will be hidden from autocomplete dropdown.'
        proxy:
          type: mapping
          mapping:
            isDisabled:
              type: integer
              label: 'Flag to disable use of Drupal as a Solr proxy for autocomplete query requests.'
            url:
              type: string
              label: 'URL of the Drupal Solr proxy.'
        direct:
          type: mapping
          mapping:
            url:
              type: string
              label: 'URL of the autocomplete direct endpoint (defaults to selected index solr server select handler).'
        username:
          type: string
          label: 'Username to be used for autocomplete direct requests basic auth.'
        password:
          type: string
          label: 'Password to be used for autocomplete direct request basic auth.'
        use_search_app_creds:
          type: integer
          label: 'Flag to indicate whether or not we are using basic auth credentials added to search app.'
    proxy:
      type: mapping
      mapping:
        isDisabled:
          type: integer
          label: 'Flag to disable use of Drupal as a Solr proxy for search query requests.'
        url:
          type: string
          label: 'URL of the Drupal Solr proxy.'
