search_api.property_configuration.federated_field:
  type: mapping
  label: 'Federated fields configuration'
  mapping:
    field_data:
      type: sequence
      label: 'The fields to be aggregated'
      sequence:
        type: sequence
        label: 'The entity type'
        sequence:
          type: string
          label: 'The bundle type'

search_api.property_configuration.site_name:
  type: mapping
  label: 'Site name processor configuration'
  mapping:
    site_name:
      type: string
      label: 'The name of the site'